version: "1.0"
stages:
  - "clone"
  - "build"
  - "push"

steps:
  clone:
    title: "Clone repository"
    type: "git-clone"
    repo: "isanka/codefresh-app"
    revision: "main"
    stage: "clone"

  build_and_push:
    title: "Build and Push Docker Image to ECR"
    type: "freestyle"
    image: amazon/aws-cli
    shell: bash
    working_directory: "${{clone}}"
    stage: "build"
    environment:
      - AWS_ACCESS_KEY_ID={{AWS_ACCESS_KEY_ID}}
      - AWS_SECRET_ACCESS_KEY={{AWS_SECRET_ACCESS_KEY}}
      - AWS_SESSION_TOKEN={{AWS_SESSION_TOKEN}}
      - AWS_REGION=ap-southeast-2
      - AWS_ACCOUNT_ID={{AWS_ACCOUNT_ID}}
      - IMAGE_REPO_NAME=demo-app
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CF_SHORT_REVISION .
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CF_SHORT_REVISION
