gitops-runtime:
  global:
    codefresh:
      accountId: 67fc4b4e32100475485b07e1
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
